### PR TITLE
Fix issue where padding was applied outside of the scroll view on the temperature page

### LINKED ISSUE #25: [BUG] Take your temperature screen has padding around the scrollview
...so it shows the glow effect in the wrong place:
Screenshot_20200322-143822

### PR DESCRIPTION
**Pull request by bkonyi**
Fixes https://github.com/coronavirus-diary/coronavirus-diary/issues/25

### CODE REVIEW

File: lib/src/ui/screens/checkup/steps/temperature.dart [hunk 1]
```diff
@@ -132,9 +132,9 @@ class _TemperatureStepState extends State<TemperatureStep> {
           (VitalsResponse response) => response.id == 'temperature',
           orElse: () => null,
         );
-        return Padding(
-          padding: EdgeInsets.all(40),
-          child: ScrollableBody(
+        return ScrollableBody(
+          child: Padding(
+            padding: const EdgeInsets.all(40.0),
```
Comment (johnsonmh) [inline lib/src/ui/screens/checkup/steps/temperature.dart]: Seems like you can leave the `.0` off as it was before?

**Review by johnsonmh — DISMISSED** [review]

File: lib/src/ui/screens/checkup/steps/temperature.dart (hunk 1 above)
Comment (bkonyi) [reply lib/src/ui/screens/checkup/steps/temperature.dart]: Sure, I can change that.

**Review by johnsonmh — APPROVED** [review]
