### PR TITLE
[testing] create a bloc delegate that forwards to FlutterError reporter

### LINKED ISSUE #88: [BUG] BlocSupervisor.delegate.onError should connect to FlutterError.onError
Otherwise the exceptions are thrown into the void, especially during tests. Otherwise, the bloc transitions can appear to get "stuck"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Adds AppHydratedBlocDelegate which is meant to be used in place of  HydratedBlocDelegate. This implements the `onError` functionality to forward to flutter's generic mechanism for reporting errors during development. This prevents them from going unnoticed in tests, where it can appear that blocs get "stuck" if they throw uncaught exceptions.

For example, if an exception was thrown in the `CheckupBlock` during development, you might see:

```
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone 11 Pro Max is available at: http://127.0.0.1:64190/9aCbjIkJiz0=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
flutter: The following _Exception was thrown In Bloc Instance of 'CheckupBloc':
flutter: Exception: asd
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      CheckupBloc._mapStartCheckupToState (package:covidnearme/src/blocs/checkup/checkup_bloc.dart:44:5)
flutter: <asynchronous suspension>
flutter: #1      CheckupBloc.mapEventToState (package:covidnearme/src/blocs/checkup/checkup_bloc.dart:29:16)
flutter: <asynchronous suspension>
flutter: #2      Bloc._bindStateSubject.<anonymous closure> (package:bloc/src/bloc.dart:155:14)
flutter: (elided 18 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Fixes https://github.com/coronavirus-diary/coronavirus-diary/issues/88

### CODE REVIEW

File: lib/main.dart [hunk 1]
```diff
@@ -1,13 +1,13 @@
...
 import 'package:flutter_bloc/flutter_bloc.dart';
 import 'package:flutter_phoenix/flutter_phoenix.dart';
-import 'package:hydrated_bloc/hydrated_bloc.dart';
 
 import 'src/app.dart';
 
 void main() async {
   WidgetsFlutterBinding.ensureInitialized();
-  BlocSupervisor.delegate = await HydratedBlocDelegate.build();
+  BlocSupervisor.delegate = await AppHydratedBlocDelegate.build();
```
Comment (dnfield) [inline lib/main.dart:10]: We should probably set the storage dir to the application documents directory rather than the default tempdir.

**Review by dnfield — APPROVED** [review]
LGTM

File: lib/main.dart (hunk 1 above)
Comment (jonahwilliams) [reply lib/main.dart:10]: Maybe file an issue for this one - this means pulling in path_provider (if we aren't already) right?

Comment (dnfield) [reply lib/main.dart:10]: Sure.  Hydrated Bloc pulls it in already
